#ifndef GS1PROTOTYPES
#define GS1PROTOTYPES

#include <gs1/parse/Parser.hpp>
namespace gs1
{
	inline gs1::PrototypeMap prototypes_cmds = {
		{"setzoomeffect", {false}},
		{"addweapon", {true}},
		{"addtiledef2", {true, true, false, false}},
		{"join", {true}},
		{ "lay", {true}},
		{ "take", {true}},
		{ "hurt", {false}},
		{ "set", {true} },
		{ "play", {true}},
		{ "unset", {true}},
		{ "setgif", {true}},
		{ "setimg", {true}},
		{ "say", {false}},
		{ "say2", {true}},
		{ "tokenize", {true}},
		{ "callnpc", {false, true}},
		{ "removecompus", {}},
		{ "setlevel", {true}},
		{ "setskincolor", {true}},
		{ "setcoatcolor", {true} },
		{ "setsleevecolor", {true} },
		{ "setshoecolor", {true} },
		{ "setbeltcolor", {true} },
		{ "setplayerdir", {true} },
		{ "putcomp", {true, false, false} },
		{ "takeplayercarry", {}},
		{ "dontblocklocal", {}},
		{ "drawoverplayer", {} },
		{ "enableweapons", {} },
		{ "disableweapons", {} },
		{ "shootarrow", {false}},
		{ "shootfireball", {false} },
		{ "shootfireblast", {false} },
		{ "shootnuke", {false} },
		{ "putbomb", {false, false, false} },
		{ "putexplosion", {false, false, false} },
		{ "putexplosion2", {false, false, false, false} },
		{ "putleaps", {false, false, false} },
		{ "shootball", {}},
		{ "timershow", {}},
		{ "playeringuild", {true}},

		{ "toinventory", {true}},
		{ "followplayer", {} },
		{ "openurl", {true} },
		{ "seturllevel", {true} },
		{"seteffect", {false, false, false, false}},
		{ "stopmidi", {}},
		{ "blockagainlocal", {}},
		{ "drawunderplayer", {}},
		{ "puthorse", {true, false, false}},
		{ "canbecarried", {}},
		{ "cannotbecarried", {}},
		{ "noplayerkilling", {}},
		{ "canbepushed", {}},
		{ "cannotbepushed", {}},
		{ "canbepulled", {}},
		{ "cannotbepulled", {}},
		{ "message", {true}},
		{ "setsword", {true, false}},
		{ "setshield", {true, false}},
		{ "putnewcomp", {true, false, false, true, false}},
		{ "putnpc", {true, true, false, false}},
		{ "destroy", {}},
		{ "freezeplayer", {false}},
		{ "sethead", {true}},
		{ "toweapons", {true}},
		{ "showimg", {false, true, false, false}},
		{ "changeimgvis", {false, false}},
		{ "hideimg", {false}},
		{ "hidesword", {false}},
		{ "hitcompu", {false, false, false, false}},
		{ "hitplayer", {false, false, false, false}},
		{ "setbow", {true}},
		{ "updateboard",{false, false, false, false}},
		{ "putobject", {true, false, false}},
		{ "setarray", {false, false}},
		{ "sleep", {false}},
		{ "hideplayer", {false}},
		{ "timereverywhere", {} },
		{ "setminimap", {true, true, false, false}},
		{ "setmap", {true, true, false, false}},
		{ "showcharacter", {}},
		{ "setplayerprop", {true, true}},
		{ "setcharprop", {true, true}},
		{ "showfile", {true}},
		{ "setstring", {true, true}},
		{ "setbackpal", {true}},
		{ "setletters", {true}},
		{ "setgifpart", {true, false, false, false, false}},
		{ "setimgpart", {true, false, false, false, false}},
		{ "setfocus", {false, false}},
		{ "resetfocus", {} },
		{ "setbody", {true}},
		{ "carryobject", {true}},
		{ "throwcarry", {}},
		{ "showlocal", {}},
		{ "hidelocal", {}},
		{"visible", {}},
		{ "dontblock", {} },
		{ "blockagain", {}},
		{ "setbacktile", {false}},
		{ "takeplayerhorse", {} },
		{ "removebomb", {}},
		{ "removearrow", {}},
		{ "removeitem", {}},
		{ "removeexplo", {}},
		{ "removehorse", {}},
		{ "explodebomb", {}},
		{ "reflectarrow", {}},
		{ "lay2", {true, false, false}},
		{ "take2", {false} },
		{ "takehorse", {false}},
		{ "playlooped", {true} },
		{ "stopmidi", {} },
		{ "stopsound", {true}},
		{ "changeimgpart", {false, false, false, false, false}},
		{ "setlevel2", {true, false, false}},
		{ "hitnpc", {false, false, false, false}},
		{ "canwarp", {} },
		{ "setani", {true, true} },
		{ "setcharani", {true, true}},
		{ "show", {} },
		{ "hide", {} },
		{ "setshape", {false, false, false} },
		{ "callweapon", { false, true } },
		{ "setcoloreffect", {false, false, false, false } },
		{ "triggeraction", {false, false, true, true } }

	};

	inline gs1::PrototypeMap prototypes_funcs = {
		{"strtofloat", {true}},
		{"strequals", {true, true}},
		{"streequals", {true, true}},
		{ "playeringuild", {true}},
		{"strcontains", {true, true}},
		{"startswith", {true, true}},
		{"strlen", {true}},
		{"playersays", {true}},
		{"playersays2", {true}},
		{"onwall", {false, false}},
		{"hasweapon", {true}},
		{"setletters", {true}},
		{"abs", {false}},
		{"sin", {false}},
		{"cos", {false}},
		{"arctan", {false}},
		{"arraylen", {false}},
		{"indexof", {true, true}},
		{"keydown", {false}},
		{"vecx", {false}},
		{"vecy", {false}},
		{"onmapx", {true}},
		{"onmapy", {true}},
	};

};

#endif