#ifndef DIALOGFEATURESH
#define DIALOGFEATURESH

namespace TilesEditor
{
	enum DialogFeatures
	{
		FEATURE_WIDTH,
		FEATURE_HEIGHT,
		FEATURE_CLIENT_CODE,
		FEATURE_SERVER_CODE,
		FEATURE_CODE,
		FEATURE_IMAGE,
		FEATURE_PROPERTIES,
		FEATURE_PARAMS
	};
};
#endif